#!/usr/bin/env perl

use strict;
use warnings;
use 5.010;

use Data::Dumper;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Terse = 1;
$Data::Dumper::Indent = 1;
$Data::Dumper::Quotekeys = 1;
sub dmp { say &Dumper; };

